imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

fos_http_cache:
    proxy_client:
        varnish:
            servers: shop.dev
            base_url: shop.dev
    cache_control:
        defaults:
            overwrite: true
        rules:
            -
                match:
                    attributes:
                        _route: homepage
                headers:
                    cache_control: { s_maxage: 3600 }
    invalidation:
        rules:
            -
                match:
                    methods: [POST]
                    attributes:
                        _route: "admin_product|admin_product_create"
                routes:
                    homepage: ~
                    products: ~
                    product: ~