security:

    encoders:
        Shop\InfrastructureBundle\Security\User:
            algorithm: bcrypt
            cost: 12

    providers:
        user_db:
            entity:
                class: Shop\InfrastructureBundle\Security\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: /(_fragment|login_check|logout|admin|cart|profile|payment)
            anonymous: ~
            form_login:
                login_path: /en/login
                check_path: /login_check
            logout:
                path:   /logout
                target: /
            oauth:
                failure_path: /en/login
                login_path: /en/login
                resource_owners:
                    facebook: "/login_check_facebook"
                    google: "/login_check_google"
                oauth_user_provider:
                    service: shop.security.oauth_user_provider

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
