Shop\Application\Command\RegisterUserCommand:
    properties:
        username:
            - NotBlank: ~
            - Email: ~
        password:
            - NotBlank: ~
            - Length:
                max: 4096